version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27018:27017"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ".docker/mongo:/data/db"
  consul:
    image: consul:1.15.4
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  traefik:
    image: traefik:v2.9
    command: 
      - "--providers.consulcatalog.endpoint.address=host.docker.internal:8500"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    depends_on:
      - consul
    ports:
      - "8080:8080"
      - "81:80"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"