version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27018:27017"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ".docker/mongo:/data/db"
  consul:
    image: consul:1.15.4
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  keycloak-db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - ".docker/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      DB_VENDOR: mysql
      DB_ADDR: host.docker.internal
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8080"
    depends_on:
      - consul
      - keycloak-db
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.consulcatalog.endpoint.address=host.docker.internal:8500"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.consulcatalog.exposedByDefault=false"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - consul
    ports:
      - "8080:8080"
      - "81:80"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
